// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/zhanglp92/rep/api/pb/item/item.proto

package pb_item

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	user "github.com/zhanglp92/rep/api/pb/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 数据最基础单元
type Item struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string               `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Type                 string               `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Colour               string               `protobuf:"bytes,4,opt,name=colour,proto3" json:"colour,omitempty"`
	Opendirection        string               `protobuf:"bytes,5,opt,name=opendirection,proto3" json:"opendirection,omitempty"`
	Size                 string               `protobuf:"bytes,6,opt,name=size,proto3" json:"size,omitempty"`
	Shape                string               `protobuf:"bytes,7,opt,name=shape,proto3" json:"shape,omitempty"`
	Glass                string               `protobuf:"bytes,8,opt,name=glass,proto3" json:"glass,omitempty"`
	Squaremeter          float32              `protobuf:"fixed32,9,opt,name=squaremeter,proto3" json:"squaremeter,omitempty"`
	Priceunit            float32              `protobuf:"fixed32,10,opt,name=priceunit,proto3" json:"priceunit,omitempty"`
	Priceset             float32              `protobuf:"fixed32,11,opt,name=priceset,proto3" json:"priceset,omitempty"`
	Price                float32              `protobuf:"fixed32,12,opt,name=price,proto3" json:"price,omitempty"`
	Remarks              string               `protobuf:"bytes,13,opt,name=remarks,proto3" json:"remarks,omitempty"`
	User                 *user.Item           `protobuf:"bytes,14,opt,name=user,proto3" json:"user,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,15,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Username             string               `protobuf:"bytes,16,opt,name=username,proto3" json:"username,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,17,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Screate              string               `protobuf:"bytes,18,opt,name=screate,proto3" json:"screate,omitempty"`
	Supdate              string               `protobuf:"bytes,19,opt,name=supdate,proto3" json:"supdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_fda99000515d91e5, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Item) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Item) GetColour() string {
	if m != nil {
		return m.Colour
	}
	return ""
}

func (m *Item) GetOpendirection() string {
	if m != nil {
		return m.Opendirection
	}
	return ""
}

func (m *Item) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Item) GetShape() string {
	if m != nil {
		return m.Shape
	}
	return ""
}

func (m *Item) GetGlass() string {
	if m != nil {
		return m.Glass
	}
	return ""
}

func (m *Item) GetSquaremeter() float32 {
	if m != nil {
		return m.Squaremeter
	}
	return 0
}

func (m *Item) GetPriceunit() float32 {
	if m != nil {
		return m.Priceunit
	}
	return 0
}

func (m *Item) GetPriceset() float32 {
	if m != nil {
		return m.Priceset
	}
	return 0
}

func (m *Item) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetRemarks() string {
	if m != nil {
		return m.Remarks
	}
	return ""
}

func (m *Item) GetUser() *user.Item {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Item) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Item) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Item) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Item) GetScreate() string {
	if m != nil {
		return m.Screate
	}
	return ""
}

func (m *Item) GetSupdate() string {
	if m != nil {
		return m.Supdate
	}
	return ""
}

type DQ struct {
	Data                 []*Item  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DQ) Reset()         { *m = DQ{} }
func (m *DQ) String() string { return proto.CompactTextString(m) }
func (*DQ) ProtoMessage()    {}
func (*DQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_fda99000515d91e5, []int{1}
}

func (m *DQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DQ.Unmarshal(m, b)
}
func (m *DQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DQ.Marshal(b, m, deterministic)
}
func (m *DQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DQ.Merge(m, src)
}
func (m *DQ) XXX_Size() int {
	return xxx_messageInfo_DQ.Size(m)
}
func (m *DQ) XXX_DiscardUnknown() {
	xxx_messageInfo_DQ.DiscardUnknown(m)
}

var xxx_messageInfo_DQ proto.InternalMessageInfo

func (m *DQ) GetData() []*Item {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "pb.item.Item")
	proto.RegisterType((*DQ)(nil), "pb.item.DQ")
}

func init() {
	proto.RegisterFile("github.com/zhanglp92/rep/api/pb/item/item.proto", fileDescriptor_fda99000515d91e5)
}

var fileDescriptor_fda99000515d91e5 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x55, 0xb2, 0x69, 0xbb, 0x9d, 0xd2, 0x05, 0x0c, 0x42, 0xa3, 0x0a, 0x89, 0xb0, 0x42, 0xa2,
	0xa7, 0x58, 0x5a, 0x4e, 0x88, 0x2b, 0x17, 0x8e, 0x44, 0xdc, 0x91, 0x93, 0x0c, 0xa9, 0x45, 0x1d,
	0x1b, 0xdb, 0x39, 0xb0, 0x3f, 0xc6, 0xef, 0x21, 0x8f, 0xdb, 0xc2, 0x9e, 0xf6, 0x62, 0xf9, 0xbd,
	0x37, 0x79, 0xcf, 0x33, 0x13, 0x90, 0xa3, 0x8e, 0x87, 0xb9, 0x6b, 0x7a, 0x6b, 0xe4, 0xfd, 0x41,
	0x4d, 0xe3, 0xd1, 0x7d, 0xbc, 0x93, 0x9e, 0x9c, 0x54, 0x4e, 0x4b, 0xd7, 0x49, 0x1d, 0xc9, 0xf0,
	0xd1, 0x38, 0x6f, 0xa3, 0x15, 0x2b, 0xd7, 0x35, 0x09, 0xee, 0xde, 0x8c, 0xd6, 0x8e, 0x47, 0x92,
	0x4c, 0x77, 0xf3, 0x0f, 0x19, 0xb5, 0xa1, 0x10, 0x95, 0x71, 0xb9, 0x72, 0xf7, 0xa8, 0xf5, 0x1c,
	0xc8, 0xf3, 0x91, 0x3f, 0xb8, 0xfd, 0x53, 0x41, 0xf5, 0x25, 0x92, 0x11, 0x37, 0x50, 0xea, 0x01,
	0x8b, 0xba, 0xd8, 0x2f, 0xda, 0x52, 0x0f, 0xe2, 0x25, 0x2c, 0xdc, 0xc1, 0x4e, 0x84, 0x65, 0x5d,
	0xec, 0xd7, 0x6d, 0x06, 0x42, 0x40, 0x15, 0x7f, 0x3b, 0xc2, 0x2b, 0x26, 0xf9, 0x2e, 0x5e, 0xc1,
	0xb2, 0xb7, 0x47, 0x3b, 0x7b, 0xac, 0x98, 0x3d, 0x21, 0xf1, 0x0e, 0xb6, 0xd6, 0xd1, 0x34, 0x68,
	0x4f, 0x7d, 0xd4, 0x76, 0xc2, 0x05, 0xcb, 0x0f, 0xc9, 0xe4, 0x18, 0xf4, 0x3d, 0xe1, 0x32, 0x3b,
	0xa6, 0x7b, 0xca, 0x0e, 0x07, 0xe5, 0x08, 0x57, 0x39, 0x9b, 0x41, 0x62, 0xc7, 0xa3, 0x0a, 0x01,
	0xaf, 0x33, 0xcb, 0x40, 0xd4, 0xb0, 0x09, 0xbf, 0x66, 0xe5, 0xc9, 0x50, 0x24, 0x8f, 0xeb, 0xba,
	0xd8, 0x97, 0xed, 0xff, 0x94, 0x78, 0x0d, 0x6b, 0xe7, 0x75, 0x4f, 0xf3, 0xa4, 0x23, 0x02, 0xeb,
	0xff, 0x08, 0xb1, 0x83, 0x6b, 0x06, 0x81, 0x22, 0x6e, 0x58, 0xbc, 0x60, 0x9e, 0x41, 0xba, 0xe3,
	0x13, 0x16, 0x32, 0x10, 0x08, 0x2b, 0x4f, 0x46, 0xf9, 0x9f, 0x01, 0xb7, 0xfc, 0x92, 0x33, 0x14,
	0x6f, 0xa1, 0x4a, 0xa3, 0xc5, 0x9b, 0xba, 0xd8, 0x6f, 0xee, 0xb6, 0x8d, 0xeb, 0x1a, 0x1e, 0x75,
	0x1a, 0x70, 0xcb, 0x92, 0xf8, 0x04, 0x9b, 0xde, 0x93, 0x8a, 0xf4, 0x3d, 0xad, 0x0e, 0x9f, 0x72,
	0xe5, 0xae, 0xc9, 0x7b, 0x6d, 0xce, 0x7b, 0x6d, 0xbe, 0x9d, 0xf7, 0xda, 0x42, 0x2e, 0x4f, 0x44,
	0x7a, 0x6b, 0x32, 0x99, 0x94, 0x21, 0x7c, 0xc6, 0xd1, 0x17, 0x9c, 0x8c, 0x67, 0x37, 0x5c, 0x8c,
	0x9f, 0x3f, 0x6e, 0x9c, 0xcb, 0xd9, 0x18, 0x61, 0x15, 0x72, 0x0e, 0x8a, 0xdc, 0xd2, 0x09, 0xb2,
	0x92, 0x0b, 0xf1, 0xc5, 0x49, 0xc9, 0xf0, 0xf6, 0x3d, 0x94, 0x9f, 0xbf, 0xa6, 0x96, 0x07, 0x15,
	0x15, 0x16, 0xf5, 0xd5, 0xb9, 0x65, 0xfe, 0x71, 0x73, 0xcb, 0x49, 0xea, 0x96, 0x1c, 0xfe, 0xe1,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x6c, 0x74, 0xf3, 0xf7, 0x02, 0x00, 0x00,
}
